### ISSUE TITLE
errors after restore

### ISSUE THREAD

**Issue by fattboy22** [kpwn/yalu#10]
===============================================] 100% Finished Moving 1 ﬁle [==================================================] 100% Finished Moving 1 ﬁle [==================================================] 100% Finished [==================================================] 100% Finished Removing 1 ﬁle [==================================================] 100% Finished Removing 1 ﬁle [==================================================] 100% Finished [==================================================] 100% Finished Sending '9e7b5b5505ebe3bcb11f8ce79f774be0f9c1e825/Manifest.plist' (12.4 KB) [==================================================] 100% Finished Sending '9e7b5b5505ebe3bcb11f8ce79f774be0f9c1e825/Manifest.mbdb' (627.3 KB) [==================================================] 100% Finished [==================================================] 100% Finished Received 3125 ﬁles from device. Backup Successful. Checksumming whole disk (Apple_HFS : 0)… ...............................................................................          whole disk (Apple_HFS : 0): veriﬁed   CRC32 $76AFD363 veriﬁed   CRC32 $C39A9C3F /dev/disk7                                         /Users/tierajones/Desktop/yalu-master/tmp_ddi "disk7" unmounted. "disk7" ejected. Found device with UUID 9e7b5b5505ebe3bcb11f8ce79f774be0f9c1e825 Backup opened Removed ﬁle tmp/9e7b5b5505ebe3bcb11f8ce79f774be0f9c1e825/951535ab91bf294166dcaf63dce9d5c6c81fc539 Found device with UUID 9e7b5b5505ebe3bcb11f8ce79f774be0f9c1e825 Backup opened File not found, creating new ﬁle Restoring backup... Waiting for device... Press [Enter] key when your device ﬁnishes restoring... Mounting DDI... Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't. [+] Device connected: iPhone7,1, iOS 8.4.1. [_] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s... [_] Received 412.82 MB of 412.82 MB (100%). [+] Done receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s. [+] Device connected: iPhone7,1, iOS 8.4.1. [_] Receiving /usr/lib/dyld... [_] Received 0.46 MB of 0.46 MB (100%). [+] Done receiving /usr/lib/dyld. Extracting /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit at 0x28fa000 into cache.IOKit Extracting /System/Library/Frameworks/IOKit.framework/IOKit at 0x28fa000 into cache.IOKit Extracting /usr/lib/system/libsystem_kernel.dylib at 0x1095f000 into cache.libsystem_kernel.dylib Unable to recognize this ﬁle - 2E2F2E2E main.m:1034:37: error: invalid suﬃx 'x' on integer constant    argss->_io_connect_add_client = IOKIT_io_connect_add_client - _DYCAC...                                    ^
                                    ^ <command line>:1:38: note: expanded from here #deﬁne IOKIT_io_connect_add_client 0x                                     ^ main.m:1034:67: error: invalid suﬃx 'x' on integer constant    argss->_io_connect_add_client = IOKIT_io_connect_add_client - _DYCAC...                                                                  ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1035:47: error: invalid suﬃx 'x' on integer constant    argss->_io_service_get_matching_service = IOKIT_io_service_get_match...                                              ^ <command line>:3:48: note: expanded from here #deﬁne IOKIT_io_service_get_matching_service 0x                                               ^ main.m:1035:87: error: invalid suﬃx 'x' on integer constant  ...= IOKIT_io_service_get_matching_service - _DYCACHE_BASE + 1;                                               ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1036:52: error: invalid suﬃx 'x' on integer constant    argss->_io_connect_method_scalarI_structureI = IOKIT_io_connect_meth...                                                   ^ <command line>:4:53: note: expanded from here #deﬁne IOKIT_io_connect_method_scalarI_structureI 0x                                                    ^ main.m:1036:97: error: invalid suﬃx 'x' on integer constant  ...= IOKIT_io_connect_method_scalarI_structureI - _DYCACHE_BASE + 1;                                                    ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1037:29: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceOpen = IOKIT_IOServiceOpen - _DYCACHE_BASE + 1;                            ^ <command line>:2:30: note: expanded from here #deﬁne IOKIT_IOServiceOpen 0x                             ^ main.m:1037:51: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceOpen = IOKIT_IOServiceOpen - _DYCACHE_BASE + 1;                                                  ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1038:30: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceClose = IOKIT_IOServiceClose - _DYCACHE_BASE + 1;                             ^ <command line>:5:31: note: expanded from here #deﬁne IOKIT_IOServiceClose 0x                              ^ main.m:1038:53: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceClose = IOKIT_IOServiceClose - _DYCACHE_BASE + 1;
    argss->_IOServiceClose = IOKIT_IOServiceClose - _DYCACHE_BASE + 1;                                                    ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1039:34: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceWaitQuiet = IOKIT_IOServiceWaitQuiet - _DYCACHE_BASE + 1;                                 ^ <command line>:6:35: note: expanded from here #deﬁne IOKIT_IOServiceWaitQuiet 0x                                  ^ main.m:1039:61: error: invalid suﬃx 'x' on integer constant    argss->_IOServiceWaitQuiet = IOKIT_IOServiceWaitQuiet - _DYCACHE_BASE + 1;                                                            ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ main.m:1040:34: error: invalid suﬃx 'x' on integer constant    argss->_host_get_io_master = LS_K_host_get_io_master - _DYCACHE_BASE + 1;                                 ^ <command line>:7:34: note: expanded from here #deﬁne LS_K_host_get_io_master 0x                                 ^ main.m:1040:60: error: invalid suﬃx 'x' on integer constant    argss->_host_get_io_master = LS_K_host_get_io_master - _DYCACHE_BASE + 1;                                                           ^ <command line>:8:24: note: expanded from here #deﬁne _DYCACHE_BASE 0x                       ^ 14 errors generated. Error opening local ﬁle for reading: PhotoData/KimJongCracks/Library/PrivateFrameworks/GPUToolsCore.framework/GPUToolsCore - No such ﬁle or directory Uploaded 92912 bytes to drugs zcat: can't stat: ./data/bootstrap.tgz (./data/bootstrap.tgz.Z): No such ﬁle or directory Uploaded 0 bytes to PhotoData/KimJongCracks/bootstrap.tar Uploaded 324288 bytes to PhotoData/KimJongCracks/tar Tap on the jailreak icon to crash the kernel (or 0wn it if you're in luck!)

**Comment by 2quignot** [comment]
You must update your xcode to the lasted xcode version

**Comment by fattboy22** [comment]
Ok il try it today

**Comment by fattboy22** [comment]
I just checked I have Xcode 7.0.1 name stilll getting this error
