### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Aleg01** [kpwn/yalu#14]
How can i get OpenSSH by Windows 8?

**Comment by spotlightishere** [comment]
How do you mean? SSH into the device on Windows 8, or use Windows 8 to install OpenSSH?

**Comment by Aleg01** [comment]
use windows 8
to install openssh into iphone

**Comment by Aleg01** [comment]
i started run.sh 
waiting for device...
and nothing

**Comment by Aleg01** [comment]
okay i just understood that this code only for mac os
