### ISSUE TITLE
How to get "./data/bootstrap.tgz"

### ISSUE THREAD

**Issue by elta** [kpwn/yalu#15]
Hi, all:
    I've installed lasted XCODE and passed most of steps. I know XCODE should be installed, Xcode command line is not enough.

Now i got the error message:
Mounting DDI...
Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't.
[+] Device connected: iPhone4,1, iOS 8.4.1.
[_] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7...
[_] Received 408.49 MB of 408.49 MB (100%).
./stage0.sh: line 49: 17014 Segmentation fault: 11  ./bin/fetchsymbols -f "$(./bin/fetchsymbols -l 2>&1 | (grep armv7 || abort ) | tr ':' '\n'|tr -d ' '|head -1)" tmp/cache
[+] Device connected: iPhone4,1, iOS 8.4.1.
[_] Receiving /usr/lib/dyld...
[_] Received 0.21 MB of 0.21 MB (100%).
[+] Done receiving /usr/lib/dyld.
Extracting /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit at 0x296f000 into cache.IOKit
Extracting /System/Library/Frameworks/IOKit.framework/IOKit at 0x296f000 into cache.IOKit
Extracting /usr/lib/system/libsystem_kernel.dylib at 0x1050a000 into cache.libsystem_kernel.dylib
2015-10-12 09:39:00.762 main[17080:2228533] cs_size = 4e0
Assertion failed: (lsrs_r0_2_popr4r5r7pc), function main, file main.m, line 538.
./make.sh: line 15: 17080 Abort trap: 6           ./main
Uploaded 268435456 bytes to PhotoData/KimJongCracks/Library/PrivateFrameworks/GPUToolsCore.framework/GPUToolsCore
Uploaded 92912 bytes to drugs
zcat: can't stat: ./data/bootstrap.tgz (./data/bootstrap.tgz.Z): No such file or directory
Uploaded 0 bytes to PhotoData/KimJongCracks/bootstrap.tar
Uploaded 324288 bytes to PhotoData/KimJongCracks/tar
Tap on the jailreak icon to crash the kernel (or 0wn it if you're in luck!)
root@ ~/work/yalu# 

My question is:
How to get ./data/bootstrap.tgz ? The repo not contain that file.

Wish you reply.

**Comment by mstg** [comment]
Its not meant to be public yet. Just use an openssh tar

**Comment by elta** [comment]
Hi @mstg, thank for reply.

I'm not got your idea. Is that mean i could use any ssh tar as bootstrap.tgz?

**Comment by mstg** [comment]
You can package anything and place as bootstrap.tar.
It will be untarred in /, if you don't know any of this you shouldn't mess around with packages.

**Comment by elta** [comment]
Your are right. This my first time to run jalbreak script, I was thought just do run.sh and jalbreak!

It looks like some error with my device too, like "Assertion failed: (lsrs_r0_2_popr4r5r7pc), function main, file main.m, line 538", it's really make me confused.

**Comment by elta** [comment]
Now i knew bootstrap.tgz should be created by myself.
