### ISSUE TITLE
bootstrap.tar

### ISSUE THREAD

**Issue by bolo1981** [kpwn/yalu#16]
Hello, i use your script for iph 6, bootstrap.tar it s missing or i can t fiind it.
can u guide me pls?

thx.

**Comment by kpwn** [comment]
I am not offering any bootstrap file so far, since there's a great risk of having to restore to iOS 9 if anything is wrong with it.

**Comment by bolo1981** [comment]
well....in that case is there an alternative for jb? or shoul i wait u to finish it?
thx Luca.

**Comment by stek29** [comment]
@kpwn Can you at least show it's structure or give me any resources for reading? I'm stuck, can't find anything :(

**Comment by mstg** [comment]
@stek29 you can literally put the contents of OpenSSH deb and the jb will untar it in `/`

**Comment by stek29** [comment]
@mstg thx, i understood already)
Now i have another problem, but it's not related to this one
