### ISSUE TITLE
Cannot connect ddi illegal instructions?

### ISSUE THREAD

**Issue by jbro129** [kpwn/yalu#17]
When I try to run mount_ddi.sh it says
Line 4:   1341 illegal instruction: 4. ./bin/deviceimagemounter "$ddi" > /dev/null

What do I do 
I have Xcode open and I have the 8.4 developer disk image 

Is there a certain place the 8.4 disk image has to be?

And when I run ./stage0.sh nothing happens it's stuck on
Waiting for device...

And when u try to run 
/yalu-master/bin/I deviceimagemounter 
It says 
ERROR: No IMAGE_FILE has been given!

So I'm guessing I have to put the image file somewhere different?
If I do, where do I put it?

**Comment by kpwn** [comment]
With xcode open, DDI is mounted automatically. deviceimagemounter is only used for people who don't have xcode open (or, for when I forget to open it).

**Comment by jbro129** [comment]
Then why is it that when I run ./stage0.sh it does nothing?
