### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kylerobson** [kpwn/yalu#28]

**Comment by kylerobson** [comment]
By the way, it failed on the line starting with hdiutil attach -nobrowse -mountpoint tmp_ddi, so I modified it to get past that point.

**Comment by kylerobson** [comment]
I changed the output to terminal instead of /dev/null. The cause of the bug is that the backup is encrypted.

Restoring modified backup...
Backup directory is "tmp"
This is an encrypted backup.
ERROR: a backup password is required to restore an encrypted backup. Cannot continue.

**Comment by awesomebing1** [comment]
Double check to see if your backup is encrypted. If it is, please deencrypt it.  You may want to copy your current backup to another folder so nothing harms it. (Search Google for how to do this.)

**Comment by kylerobson** [comment]
Thanks I'm working on it... iTunes is being slow.

**Comment by kylerobson** [comment]
Got further by passing a --password argument to idevicebackup2, but it ultimately fails.

...
Sending 'a78541a8e9a9bd67cc840e542302024ba76c38e0/a3388bc3048d99c38f0f6c485177ebcc64de0514' (256 Bytes)
[==================================================] 100% Finished
ErrorCode 205: Encryption key missing: /var/mobile/Media/PhotoData/KimJongCracks/a/a/MobileReplayer (951535ab91bf294166dcaf63dce9d5c6c81fc539) (MBErrorDomain/205)
The device should reboot now.
Restore Failed (Error Code 205).

**Comment by awesomebing1** [comment]
Did you decrypt the password in iTunes itself?

**Comment by kylerobson** [comment]
No I just passed the --password argument to the idevicebackup2 command. iTunes isn't allowing me to uncheck the "Encrypt iPhone Backup" option. I think I have to delete some profiles or something if that's necessary.

**Comment by awesomebing1** [comment]
Is the option grayed out?

**Comment by kylerobson** [comment]
Yes. I deleted the profiles from the phone via Settings app -> General -> Profiles. Now I unchecked it successfully. Script now says "backup will be unencrypted" so I removed the --password argument from idevicebackup2.

Got further! Now it's rebooting. So basically lessons learned: uncheck encryption in iTunes and hard coding the path for this line may be a quick fix for the script to work (could probably adapt script to work without hard coding): hdiutil attach -nobrowse -mountpoint tmp_ddi "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/8.4/DeveloperDiskImage.dmg"

**Comment by kylerobson** [comment]
Got a bunch of errors after the restore because iTunes was open. I unchecked the box to automatically sync the device in iTunes, closed iTunes, Xcode was already open, unplugged and replugged the device. Tried again and got to the end but with a couple errors. Tapped the Jailbreak app and it closed the app immediately. How do I know if it worked?

Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't.
Fetching symbols...
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s...
[*] Received 412.46 MB of 412.46 MB (100%).
[+] Done receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s.
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /usr/lib/dyld...
[*] Received 0.46 MB of 0.46 MB (100%).
[+] Done receiving /usr/lib/dyld.
Compiling jailbreak files...
./run.sh: line 128: ./bin/jtool: No such file or directory
./run.sh: line 129: ./bin/jtool: No such file or directory
./run.sh: line 130: cd: ./data/dyldmagic: No such file or directory
./run.sh: line 131: ./make.sh: No such file or directory
Copying files to device...
./run.sh: line 135: ./bin/afcclient: No such file or directory
./run.sh: line 136: ./bin/afcclient: No such file or directory
./run.sh: line 137: ./tmp/bootstrap.tar: No such file or directory
./run.sh: line 138: ./bin/afcclient: No such file or directory
./run.sh: line 139: ./bin/afcclient: No such file or directory
Tap on the jailbreak icon to crash the kernel (or 0wn it if you're in luck!)

**Comment by awesomebing1** [comment]
By any chance, are you running the script by opening it in the finder?

**Comment by kylerobson** [comment]
I git cloned into ~/Projects/yalu, cd ~/Projects/yalu, ./run.sh

Strangely most of the files mentioned above where it says "No such file or directory" do exist. However ./make.sh does not exist.

**Comment by kylerobson** [comment]
I see the issue. 

cd tmp
lipo ...
fix by: cd ..

**Comment by kylerobson** [comment]
Looks like there are a couple mistakes related to changing directory and then not changing back. It also "cd"s to data/dyldmagic and doesn't go back.

**Comment by kylerobson** [comment]
Here's the best output I've gotten so far after fixing the script up a little. 

Kyles-MacBook-Pro:yalu kyle$ ./run2.sh 
Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't.
Fetching symbols...
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s...
[*] Received 412.46 MB of 412.46 MB (100%).
[+] Done receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s.
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /usr/lib/dyld...
[*] Received 0.46 MB of 0.46 MB (100%).
[+] Done receiving /usr/lib/dyld.
Compiling jailbreak files...
jtool: can't open cache - No such file or directory
jtool: can't open cache - No such file or directory
Unable to recognize this file - 2E2F2E2E
main.m:1034:37: error: invalid suffix 'x' on integer constant
    argss->_io_connect_add_client = IOKIT_io_connect_add_client - _DYCACHE_BASE + 1;
                                    ^
<command line>:1:38: note: expanded from here
#define IOKIT_io_connect_add_client 0x
                                     ^
main.m:1034:67: error: invalid suffix 'x' on integer constant
    argss->_io_connect_add_client = IOKIT_io_connect_add_client - _DYCACHE_BASE + 1;
                                                                  ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1035:47: error: invalid suffix 'x' on integer constant
    argss->_io_service_get_matching_service = IOKIT_io_service_get_matching_service - _DYCACHE_BASE + 1;
                                              ^
<command line>:3:48: note: expanded from here
#define IOKIT_io_service_get_matching_service 0x
                                               ^
main.m:1035:87: error: invalid suffix 'x' on integer constant
    argss->_io_service_get_matching_service = IOKIT_io_service_get_matching_service - _DYCACHE_BASE + 1;
                                                                                      ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1036:52: error: invalid suffix 'x' on integer constant
    argss->_io_connect_method_scalarI_structureI = IOKIT_io_connect_method_scalarI_structureI - _DYCACHE_BASE + 1;
                                                   ^
<command line>:4:53: note: expanded from here
#define IOKIT_io_connect_method_scalarI_structureI 0x
                                                    ^
main.m:1036:97: error: invalid suffix 'x' on integer constant
    argss->_io_connect_method_scalarI_structureI = IOKIT_io_connect_method_scalarI_structureI - _DYCACHE_BASE + 1;
                                                                                                ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1037:29: error: invalid suffix 'x' on integer constant
    argss->_IOServiceOpen = IOKIT_IOServiceOpen - _DYCACHE_BASE + 1;
                            ^
<command line>:2:30: note: expanded from here
#define IOKIT_IOServiceOpen 0x
                             ^
main.m:1037:51: error: invalid suffix 'x' on integer constant
    argss->_IOServiceOpen = IOKIT_IOServiceOpen - _DYCACHE_BASE + 1;
                                                  ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1038:30: error: invalid suffix 'x' on integer constant
    argss->_IOServiceClose = IOKIT_IOServiceClose - _DYCACHE_BASE + 1;
                             ^
<command line>:5:31: note: expanded from here
#define IOKIT_IOServiceClose 0x
                              ^
main.m:1038:53: error: invalid suffix 'x' on integer constant
    argss->_IOServiceClose = IOKIT_IOServiceClose - _DYCACHE_BASE + 1;
                                                    ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1039:34: error: invalid suffix 'x' on integer constant
    argss->_IOServiceWaitQuiet = IOKIT_IOServiceWaitQuiet - _DYCACHE_BASE + 1;
                                 ^
<command line>:6:35: note: expanded from here
#define IOKIT_IOServiceWaitQuiet 0x
                                  ^
main.m:1039:61: error: invalid suffix 'x' on integer constant
    argss->_IOServiceWaitQuiet = IOKIT_IOServiceWaitQuiet - _DYCACHE_BASE + 1;
                                                            ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
main.m:1040:34: error: invalid suffix 'x' on integer constant
    argss->_host_get_io_master = LS_K_host_get_io_master - _DYCACHE_BASE + 1;
                                 ^
<command line>:7:34: note: expanded from here
#define LS_K_host_get_io_master 0x
                                 ^
main.m:1040:60: error: invalid suffix 'x' on integer constant
    argss->_host_get_io_master = LS_K_host_get_io_master - _DYCACHE_BASE + 1;
                                                           ^
<command line>:8:24: note: expanded from here
#define _DYCACHE_BASE 0x
                       ^
14 errors generated.
Copying files to device...
Error opening local file for reading: PhotoData/KimJongCracks/Library/PrivateFrameworks/GPUToolsCore.framework/GPUToolsCore - No such file or directory
Uploaded 92912 bytes to drugs
zcat: can't stat: ./data/bootstrap.tgz (./data/bootstrap.tgz.Z): No such file or directory
Uploaded 0 bytes to PhotoData/KimJongCracks/bootstrap.tar
Uploaded 324288 bytes to PhotoData/KimJongCracks/tar
Tap on the jailbreak icon to crash the kernel (or 0wn it if you're in luck!)

**Comment by awesomebing1** [comment]
Hm. Can’t help you there. Someone else may know how to help you, though.

**Comment by kylerobson** [comment]
I changed the make file to use 0x0 instead of 0x and I get the following errors instead:

Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't.
Fetching symbols...
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s...
[*] Received 412.46 MB of 412.46 MB (100%).
[+] Done receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s.
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /usr/lib/dyld...
[*] Received 0.46 MB of 0.46 MB (100%).
[+] Done receiving /usr/lib/dyld.
Compiling jailbreak files...
jtool: can't open cache - No such file or directory
jtool: can't open cache - No such file or directory
Unable to recognize this file - 2E2F2E2E
Assertion failed: (g_cs_size > 0), function dump_dyld_segments, file main.m, line 330.
./make.sh: line 6:  7743 Abort trap: 6           ./main
Copying files to device...
Error opening local file for reading: PhotoData/KimJongCracks/Library/PrivateFrameworks/GPUToolsCore.framework/GPUToolsCore - No such file or directory
Uploaded 92912 bytes to drugs
zcat: can't stat: ./data/bootstrap.tgz (./data/bootstrap.tgz.Z): No such file or directory
Uploaded 0 bytes to PhotoData/KimJongCracks/bootstrap.tar
Uploaded 324288 bytes to PhotoData/KimJongCracks/tar
Tap on the jailbreak icon to crash the kernel (or 0wn it if you're in luck!)

**Comment by awesomebing1** [comment]
It looks like jtool can't find the cache file. Perhaps it's not in the right directory?

**Comment by kylerobson** [comment]
Yeah I got that. Here's the latest issue. This one is a bit beyond me.

Kyles-MacBook-Pro:yalu kyle$ ./run2.sh 
Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't.
Fetching symbols...
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s...
[*] Received 412.46 MB of 412.46 MB (100%).
[+] Done receiving /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s.
[+] Device connected: iPhone6,1, iOS 8.4.1.
[*] Receiving /usr/lib/dyld...
[*] Received 0.46 MB of 0.46 MB (100%).
[+] Done receiving /usr/lib/dyld.
Compiling jailbreak files...
Extracting /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit at 0x28fa000 into cache.IOKit
Extracting /System/Library/Frameworks/IOKit.framework/IOKit at 0x28fa000 into cache.IOKit
Extracting /usr/lib/system/libsystem_kernel.dylib at 0x1091b000 into cache.libsystem_kernel.dylib
Unable to recognize this file - 2E2F2E2E
Assertion failed: (g_cs_size > 0), function dump_dyld_segments, file main.m, line 330.
./make.sh: line 6:  8513 Abort trap: 6           ./main
Copying files to device...
Error opening local file for reading: PhotoData/KimJongCracks/Library/PrivateFrameworks/GPUToolsCore.framework/GPUToolsCore - No such file or directory
Uploaded 92912 bytes to drugs
zcat: can't stat: ./data/bootstrap.tgz (./data/bootstrap.tgz.Z): No such file or directory
Uploaded 0 bytes to PhotoData/KimJongCracks/bootstrap.tar
Uploaded 324288 bytes to PhotoData/KimJongCracks/tar
Tap on the jailbreak icon to crash the kernel (or 0wn it if you're in luck!)

**Comment by awesomebing1** [comment]
Looks like the logic in https://github.com/kpwn/yalu/blob/master/data/dyldmagic/main.m is failing. I don’t know how to fix that either.




Could you please do a pull request for all of the lines you have changed so far to get to this point? It would help a lot of us.

**Comment by qfdk** [comment]
i will pull to fix it😜
