### ISSUE TITLE
Still waiting for device nothing appears

### ISSUE THREAD

**Issue by 2quignot** [kpwn/yalu#3]
Testing with an iPad Air  (WiFi) iOS 8.4.1 on Mac OS 10.9 -> XCODE 5.1.1

**Comment by JJGadgets** [comment]
Do you have the developer disk image for 8.4?

**Comment by JJGadgets** [comment]
I think it is not supported in Mavericks, I tried to change DDI location to my Desktop, but that did not work.

**Comment by 2quignot** [comment]
Hello,  don't have the disk image 8.4 i download now and retry to Jailbreak this is the problem ? Or there is an another problem ? Thank you :)

**Comment by 2quignot** [comment]
I have the same problem device waiting nothing appears

**Comment by 2quignot** [comment]
Problem fixed it's a general problem with /bin of yalu but fixed by me :)

**Comment by ABCS7** [comment]
Can I ask what you did to fix it? I'm having the same problem getting stuck on the waiting for device.

**Comment by jbro129** [comment]
How did you fix it?
