### ISSUE TITLE
Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't it.

### ISSUE THREAD

**Issue by 2quignot** [kpwn/yalu#4]
I have this error message then try to mount DDI "Couldn't mount DDI. Not an issue if Xcode's running, an issue if it isn't it."

**Comment by matteyeux** [comment]
La nouvelle version fixe le probleme

**Comment by ghost** [comment]
Close Xcode if it's running if it's not then post the log below

**Comment by mstg** [comment]
@Adryd That's wrong. If Xcode is running then it should not be a problem, but if Xcode is not running then there is. So if Xcode is running, then dont worry.

**Comment by 2quignot** [comment]
Now work the problem is not xcode but libimobiledevice it's now fixed by me manually thank you for your help :)
