### ISSUE TITLE
cannot find an available link of Cydia-8.4r3-Raw.txz

### ISSUE THREAD

**Issue by Izib** [kpwn/yalu#43]
I'm trying yalu code to jb my iphone6.
Compressed bootstarp.tgz with OpenSSH&OpenSSL and it looks like the jb code works.(got 6+ ret)
![image](https://cloud.githubusercontent.com/assets/2154257/15992205/293e24b6-30fa-11e6-9ceb-2ac2d559f673.png)

But all links of  Cydia-8.4r3-Raw.txz is not available now. 
Could you plz share the Cydia-8.4r3-Raw.txz on somewhere?

**Comment by kpwn** [comment]
Hey, that looks good. But remember to remove patcyh and don’t attempt to untether.

**Comment by Izib** [comment]
@kpwn Thanx. 
Can you share the Cydia-8.4r3-Raw.txz file to me?

**Comment by Izib** [comment]
I find the way to fix this. close issue
