### ISSUE TITLE
Need the download for cydia, openssh, and openssl gzip tar's

### ISSUE THREAD

**Issue by EvilSeabass** [kpwn/yalu#47]
Hello,
I need to create a bootstrap for Yalu.
Could someone please upload one that works and has patcyh removed and is ready to go or give me the links for where I can find cydia, openssh, and OpenSSL for iOS 8.4.1? I'm running an iPod 5 running iOS 8.4.1

**Comment by EvilSeabass** [comment]
@kpwn

**Comment by EvilSeabass** [comment]
nvm got it

**Comment by stevezaluk** [comment]
Where did you find it? I would like to kno :)
