### ISSUE TITLE
make.sh : cannot compile main.m

### ISSUE THREAD

**Issue by matteyeux** [kpwn/yalu#5]
sh-3.2$ ./make.sh
2015-10-04 12:51:03.409 main[1633:66359] cs_size = 4e0
Assertion failed: (lsrs_r0_2_popr4r5r7pc), function main, file main.m, line 538.
./make.sh: line 6:  1633 Abort trap: 6           ./main
sh-3.2$

**Comment by kpwn** [comment]
known issue for non armv7s dylds. will be fixing asap, just got back home

**Comment by matteyeux** [comment]
Does the new updates fix the non armv7s issue ?

**Comment by kpwn** [comment]
Not yet. currently trying to get my 6 jailbroken first.

**Comment by yun0ji** [comment]
Fixed the problem ?

**Comment by yun0ji** [comment]
Does the issue fixed already ?

**Comment by matteyeux** [comment]
No

**Comment by ericcastro** [comment]
has this issue been solved ?

**Comment by matteyeux** [comment]
Nope Yalu's development has halted due to constant harassement :(
