### ISSUE TITLE
iPad 2 stuck at "* Waiting for device..."

### ISSUE THREAD

**Issue by anonfantom** [kpwn/yalu#56]
@kpwn Please tell me how can i fix this issue with my iPad 2 with iOS 8.4.1 
My MacOS version is 10.12.3 and the last public Xcode version 
so is there any help 
? ? ?

**Comment by victor1342** [comment]
maybe you need to use sudo? try: `sudo sh ./run.sh`

**Comment by abuhassan-dev** [comment]
@victor1342 i think its not supported did you try it ?

**Comment by NicholasLAranda** [comment]
@anonfantom THIS IS NOT A SUPPORT PAGE FOR iOS 8.X JAILBREAKS!!!

Go to https://www.Reddit.com/r/JailBreak if you need assistance.

Please close this.

**Comment by DarknesGaming** [comment]
Here's my question: Why are you on iOS 8.4.1? It's so old (and easier to hack into).
@RypeDub420 this was never a support page in the first place. Mind the caps. xD

**Comment by Teuns** [comment]
@darknesgaming easier to hack into? What? There are none public jb's for it except this one, which is even incomplete.

**Comment by eob2000** [comment]
if you didn't fix it already I had the same issue with my iPhone 4s. `sudo chmod -R 777 /var/db/lockdown/`fixed it for me
