### ISSUE TITLE
There is an error!

### ISSUE THREAD

**Issue by devxu** [kpwn/yalu#7]
Found device with UUID 9ase35982x296cf583374ef769zoraf25d71f0j5
Backup opened
Found device with UUID 9ase35982x296cf583374ef769zoraf25d71f0j5
Backup opened
File not found, creating new file
Restoring backup...
Error. Exiting...
Waiting for device...
Press [Enter] key when your device finishes restoring...

**Comment by mstg** [comment]
Disable find my iphone

**Comment by devxu** [comment]
Thanks. It's resolved.
